name: micro-blog

services:
  micro-blog-db:
    image: postgres:16.1
    shm_size: 128mb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "micro-blog-db-volume:/dev/shm"
    networks:
      micro-blog-network:
        aliases:
          - "sql"
    env_file:
      - .env

  micro-blog-pgadmin:
    image: dpage/pgadmin4:8.1
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:80"
    depends_on:
      - micro-blog-db
    networks:
      - micro-blog-network
    env_file:
      - .env

  micro-blog-redis:
    image: redis:8.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  micro_blog-rabbitmq:
    image: rabbitmq:4.1.4-management
    restart: always
    hostname: rabbitmq_host
    ports:
      - "${RABBITMQ_PORT_1}:${RABBITMQ_PORT_1}"
      - "${RABBITMQ_PORT_2}:${RABBITMQ_PORT_2}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/

volumes:
  micro-blog-db-volume:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  micro-blog-network:
    driver: bridge